allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-image-slem-61-v100
parameters:
  backingImage: vmi-5a8f627e-b1a3-4ae1-b7a0-261388de2cad
  migratable: 'true'
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate