apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-name-02
  namespace: project-name
spec:
  runStrategy: RerunOnFailure
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network.harvesterhci.io/mgmt
                    operator: In
                    values:
                      - 'true'
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              macAddress: 02:35:4b:66:c2:56
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 10922Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: vm-name-02
      networks:
        - multus:
            networkName: harvester-public/main-lan
          name: default
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: vm-name-02-disk-0
        - cloudInitNoCloud:
            networkDataSecretRef:
              name: cloudinit-vm-name-02
            secretRef:
              name: cloudinit-vm-name-02
          name: cloudinitdisk